# This file was generated by GoReleaser. DO NOT EDIT.
cask "repo-lister" do
  name "repo-lister"
  desc "Container image management tool using Kubernetes credentials"
  homepage "https://github.com/btwseeu78/repo-lister"
  version "0.0.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "repo-lister"

  on_linux do
    on_intel do
      url "https://github.com/btwseeu78/repo-lister/releases/download/v#{version}/repo-lister_#{version}_linux_x86_64.tar.gz"
      sha256 "8a4833b2a61f67befa90c39ffef6ea16d7b504f3a01001dd413ef77c86a82275"
    end
    on_arm do
      url "https://github.com/btwseeu78/repo-lister/releases/download/v#{version}/repo-lister_#{version}_linux_arm64.tar.gz"
      sha256 "d2fdee18e0c164421fa8005e272c8f1a750278934282922f016f6c5c8485b004"
    end
  end

  # No zap stanza required
end
